/*
 * Copyright 2020 Arthur Sadykov.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.isarthur.netbeans.editor.generator.java.ui;

import java.util.List;
import javax.lang.model.element.Element;
import javax.swing.DefaultListModel;
import org.openide.DialogDescriptor;

/**
 *
 * @author Arthur Sadykov
 */
public class LocalMembersAndVarsPanel extends javax.swing.JPanel {

    private final DefaultListModel<Element> listModel = new DefaultListModel<>();
    private DialogDescriptor dialogDescriptor;

    /**
     * Creates new form LocalMembersAndVarsPanel
     */
    private LocalMembersAndVarsPanel() {
        initComponents();
        localMembersAndVarsList.addListSelectionListener(e -> {
            dialogDescriptor.setValid(true);
        });
    }

    public static LocalMembersAndVarsPanel create() {
        return new LocalMembersAndVarsPanel();
    }
    
    public void setDialogDescriptor(DialogDescriptor dialogDescriptor) {
        this.dialogDescriptor = dialogDescriptor;
    }

    public void addElements(List< Element> elements) {
        elements.forEach(listModel::addElement);
    }

    public Element getSelectedElement() {
        return localMembersAndVarsList.getSelectedValue();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localMembersAndVarsScrollPane = new javax.swing.JScrollPane();
        localMembersAndVarsList = new javax.swing.JList<>();

        localMembersAndVarsList.setModel(listModel);
        localMembersAndVarsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        localMembersAndVarsScrollPane.setViewportView(localMembersAndVarsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(localMembersAndVarsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(localMembersAndVarsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Element> localMembersAndVarsList;
    private javax.swing.JScrollPane localMembersAndVarsScrollPane;
    // End of variables declaration//GEN-END:variables
}
